<?php
/**
 * @file
 * Code for the imagex_workflow feature.
 */

include_once 'imagex_workflow.features.inc';
// Forced the inclusion of the workbench_moderation states and transitions
// as they are not auto-included during site install feature building using the
// `features_include_defaults` function as the component is not recognized as includable.
// If these files are not included, the foreach loop in `workbench_moderation_states_features_rebuild`
// presents a warning due to `$defaults` equalling false.
include_once 'imagex_workflow.features.workbench_moderation_states.inc';
include_once 'imagex_workflow.features.workbench_moderation_transitions.inc';

/**
 * Implements hook_date_popup_pre_validate_alter().
 *
 * Assists in providing a default time for scheduler's publish_on and unpublish_on
 * fields should only a date be presented. The date_popup api will present a form error
 * should only the date be present and not the time during validation.
 */
function imagex_workflow_date_popup_pre_validate_alter(&$element, &$form_state, &$input) {
  if (in_array($element['#name'], array('publish_on', 'unpublish_on')) && isset($form_state['values'][$element['#name']])) {
    if (!empty($form_state['values'][$element['#name']]['date']) && empty($form_state['values'][$element['#name']]['time'])) {
      $form_state['values'][$element['#name']]['time'] = '00:00:00';
    }
    $input = $form_state['values'][$element['#name']];
  }
}

/**
 * Implements hook_form_alter().
 */
function imagex_workflow_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'workbench_access_section_form') {
    $form['#submit'][] = 'imagex_workflow_workbench_submit';
  }
}

/**
 * @param $form
 * @param $form_state
 */
function imagex_workflow_workbench_submit(&$form, &$form_state) {
  if (!empty($form_state['input']['sections']) && db_table_exists('workbench_access_user')) {
    foreach ($form_state['input']['sections']['workbench_section'] as $key => $row) {
      if (!empty($row)) {
        db_merge('workbench_access_user')
          ->key(array('access_id' => $key))
          ->fields(array(
            'uid' => 1,
            'access_scheme' => 'taxonomy',
          ))
          ->execute();
      }
      else {
        db_delete('workbench_access_user')
          ->condition('uid', 1)
          ->condition('access_id', $key)
          ->execute();
      }
    }
  }
}
